<form action="<?php echo $this->getUrl('testimonials/index/formpost')?>" method="post" id="testimonials">
 <ul class="form-list">
 <li class="fields">
<label for="name"><?php echo $this->__('Name: ')?></label>
<div class="input-box">
<input type="text" name="testimonial_name" class="input-text required-entry validate-text"/>
</div>
</li>
 <li class="fields">
<label for="address"><?php echo $this->__('City, State: ')?></label>
<div class="input-box">
<input type="text" name="testimonial_address" class="input-text required-entry validate-text"/>
</div>
</li>
 <li class="fields">
<label for="email"><?php echo $this->__('Email: ')?></label>
<div class="input-box">
<input type="text" name="testimonial_email" class="input-text required-entry validate-email"/>
</div>
</li>
 <li class="wide">
<div class="input-box">
<label for="name"><?php echo $this->__('Testimonial: ')?></label>
<textarea name="testimonial_comment"rows="4" cols="50" class="input-text required-entry validate-text"></textarea>
</div>
</li>

<li>
<?php
echo $this->getChildHtml('captcha'); 
?>
<input type="submit"/>
</li>
</ul>
</form>
<script type="text/javascript">
//<![CDATA[
    var testimonialForm = new VarienForm('testimonials', true);
//]]>
</script>
