<div class="customer-account-header">
	<ul class="links">
		<li><a href="<?php echo $this->getUrl('customer/account/index');?>"><?php echo $this->__('Dashboard')?></a></li>
		<li><a href="<?php echo $this->getUrl('hdccustomer/index/pricing');?>"><?php echo $this->__('Pricing');?></a></li>
		<li><a href="<?php echo $this->getUrl('hdccustomer/index/forms');?>"><?php echo $this->__('Forms');?></a></li>
		<li><a href="#"><?php echo $this->__('Distributors');?></a></li>
		<li><a href="#"><?php echo $this->__('Guarantee');?></a></li>
		<li><a href="#"><?php echo $this->__('Shipping');?></a></li>
	</ul>
</div>